package org.projects.challenges.fibonacci;

import java.sql.Array;
import java.util.ArrayList;
import java.util.List;

/*
Write a method that returns the sum of all even Fibonacci numbers.
Consider all Fibonacci numbers that are less than or equal to n.
Each new element in the Fibonacci sequence is generated by adding the previous two elements.
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*/
public class Fibonacci_Main {
    public static void main(String[] args) {
        Solution solution = new Solution();
        System.out.println(solution.execute(20));
    }
}


class Solution{
    int a = 0;
    int b = 1;
    int c = 0;

    List<Integer> execute(int n){
        List<Integer> intList = new ArrayList<Integer>();
        for (int i = 0; i < n; i++) {
            c = a+b;
            a = b;
            b = c;
            intList.add(c);
        }
        return intList;
    }

}
